task:
  name: Linux gcc
  container:
    image: gcc:latest
    cpu: 1
    memory: 256MB
  info_script:
    - cc --version
  build_script:
    - make
    - test -x tailmerge
    - test -z "$(find -type f -executable -not -name '*.*' -not -name tailmerge)"
  test_script:
    - make all
    - make test
  clean_script:
    - make clean
    - test -z "$(find -type f -executable -not -name '*.*')"

task:
  name: Linux arm gcc
  arm_container:
    image: gcc:latest
    cpu: 1
    memory: 256MB
  test_script: make test
