[package]
name = "logmerge"
version = "0.1.0"
authors = ["Torbjørn Birch Moltu <t.b.moltu@lyse.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
